import { createHash, createCipheriv, createDecipheriv, randomBytes, timingSafeEqual } from "crypto";

/** 10-second timeout for all external OAuth fetches */
const FETCH_TIMEOUT_MS = 10_000;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface GitHubUser {
  login: string;
  name: string | null;
  avatar_url: string;
}

// ---------------------------------------------------------------------------
// OAuth URL
// ---------------------------------------------------------------------------

/**
 * Build the GitHub OAuth authorization URL with `read:user` and `user:email` scopes.
 *
 * @param clientId - GitHub OAuth App client ID
 * @param redirectUri - Callback URL GitHub redirects to after authorization
 * @param state - CSRF state token (generated by {@link createStateCookie})
 * @returns Fully qualified GitHub authorization URL with query parameters
 */
export function buildAuthUrl(clientId: string, redirectUri: string, state: string): string {
  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: "read:user user:email",
    state,
  });
  return `https://github.com/login/oauth/authorize?${params.toString()}`;
}

// ---------------------------------------------------------------------------
// CSRF state cookie
// ---------------------------------------------------------------------------

const STATE_COOKIE_NAME = "chapa_oauth_state";

function isSecureOrigin(): boolean {
  const base = process.env.NEXT_PUBLIC_BASE_URL?.trim() ?? "";
  return base.startsWith("https://");
}

function cookieFlags(): string {
  const secure = isSecureOrigin() ? " Secure;" : "";
  return `HttpOnly;${secure} SameSite=Lax; Path=/`;
}

/**
 * Generate a cryptographically random CSRF state token and return it as a
 * `Set-Cookie` header value (HttpOnly, SameSite=Lax, 10-minute Max-Age).
 *
 * @returns Object with `state` (hex token) and `cookie` (Set-Cookie header value)
 */
export function createStateCookie(): { state: string; cookie: string } {
  const state = randomBytes(16).toString("hex");
  const cookie = `${STATE_COOKIE_NAME}=${state}; ${cookieFlags()}; Max-Age=600`;
  return { state, cookie };
}

/**
 * Validate the OAuth CSRF state parameter against the value stored in the
 * `chapa_oauth_state` cookie.
 *
 * Uses `crypto.timingSafeEqual` for constant-time comparison to prevent
 * timing-based side-channel attacks on the state token. Both buffers are
 * compared only when their lengths match; a length mismatch returns `false`
 * immediately (safe because length is not secret).
 *
 * @param cookieHeader - Raw `Cookie` header string from the incoming request.
 *   The state cookie is extracted by name from this semicolon-delimited string.
 * @param queryState - The `state` query parameter returned by GitHub's OAuth
 *   redirect. Must match the cookie value exactly.
 * @returns `true` if both values are present and identical; `false` otherwise.
 *
 * @example
 * ```ts
 * const isValid = validateState(
 *   request.headers.get("cookie"),
 *   url.searchParams.get("state"),
 * );
 * if (!isValid) return new Response("CSRF validation failed", { status: 403 });
 * ```
 */
export function validateState(
  cookieHeader: string | null,
  queryState: string | null,
): boolean {
  if (!cookieHeader || !queryState) return false;
  const match = cookieHeader
    .split(";")
    .map((c) => c.trim())
    .find((c) => c.startsWith(`${STATE_COOKIE_NAME}=`));
  if (!match) return false;
  const cookieState = match.slice(STATE_COOKIE_NAME.length + 1);
  const cookieBuf = Buffer.from(cookieState, "utf8");
  const queryBuf = Buffer.from(queryState, "utf8");
  if (cookieBuf.length !== queryBuf.length) return false;
  return timingSafeEqual(cookieBuf, queryBuf);
}

/**
 * Return a `Set-Cookie` header value that immediately expires the CSRF state cookie.
 *
 * @returns Set-Cookie header string with Max-Age=0
 */
export function clearStateCookie(): string {
  return `${STATE_COOKIE_NAME}=; ${cookieFlags()}; Max-Age=0`;
}

// ---------------------------------------------------------------------------
// Token exchange
// ---------------------------------------------------------------------------

/**
 * Exchange a GitHub OAuth authorization code for an access token.
 *
 * POSTs to `https://github.com/login/oauth/access_token` with JSON encoding.
 * Times out after 10 seconds.
 *
 * @param code - The authorization code from GitHub's OAuth callback
 * @param clientId - GitHub OAuth App client ID
 * @param clientSecret - GitHub OAuth App client secret
 * @returns The access token string, or `null` on error or invalid response
 */
export async function exchangeCodeForToken(
  code: string,
  clientId: string,
  clientSecret: string,
): Promise<string | null> {
  try {
    const res = await fetch("https://github.com/login/oauth/access_token", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        client_id: clientId,
        client_secret: clientSecret,
        code,
      }),
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });

    const data = await res.json();
    if (data.error || !data.access_token) return null;
    return data.access_token as string;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Fetch authenticated user
// ---------------------------------------------------------------------------

/**
 * Fetch the authenticated GitHub user's profile (login, name, avatar_url).
 *
 * Calls `GET https://api.github.com/user` with the provided OAuth token.
 * Times out after 10 seconds.
 *
 * @param accessToken - GitHub OAuth access token
 * @returns A {@link GitHubUser} object, or `null` on error or non-OK response
 */
export async function fetchGitHubUser(
  accessToken: string,
): Promise<GitHubUser | null> {
  try {
    const res = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: "application/vnd.github+json",
      },
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    if (!res.ok) return null;
    const data = await res.json();
    return {
      login: data.login,
      name: data.name ?? null,
      avatar_url: data.avatar_url,
    };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Fetch primary verified email (requires user:email scope)
// ---------------------------------------------------------------------------

interface GitHubEmail {
  email: string;
  primary: boolean;
  verified: boolean;
}

/**
 * Fetch the user's primary verified email from GitHub.
 * Requires the `user:email` OAuth scope. Returns null if no primary
 * verified email is found or on any error.
 */
export async function fetchGitHubUserEmail(
  accessToken: string,
): Promise<string | null> {
  try {
    const res = await fetch("https://api.github.com/user/emails", {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: "application/vnd.github+json",
      },
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    if (!res.ok) return null;

    const emails: GitHubEmail[] = await res.json();
    const primary = emails.find((e) => e.primary && e.verified);
    return primary?.email ?? null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Token encryption (AES-256-GCM)
// ---------------------------------------------------------------------------

function deriveKey(secret: string): Buffer {
  return createHash("sha256").update(secret).digest();
}

/**
 * Encrypt a plaintext token using AES-256-GCM with authenticated encryption.
 *
 * The encryption key is derived by SHA-256 hashing the provided secret.
 * A fresh 12-byte random IV is generated for every call, ensuring that
 * encrypting the same token twice produces different ciphertexts.
 *
 * **Output format:** `iv:authTag:ciphertext` — three colon-separated hex strings.
 * The 16-byte GCM authentication tag provides tamper detection on decryption.
 *
 * @param token - The plaintext string to encrypt (typically a GitHub OAuth access token).
 * @param secret - The secret used to derive the AES-256 key via SHA-256.
 *   In production this comes from `NEXTAUTH_SECRET`.
 * @returns A hex-encoded string in the format `iv:authTag:ciphertext`.
 *
 * @example
 * ```ts
 * const encrypted = encryptToken(accessToken, process.env.NEXTAUTH_SECRET!);
 * // "a1b2c3...:d4e5f6...:789abc..."
 * ```
 */
export function encryptToken(token: string, secret: string): string {
  const key = deriveKey(secret);
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const encrypted = Buffer.concat([
    cipher.update(token, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  // Format: iv:authTag:ciphertext (all hex)
  return `${iv.toString("hex")}:${authTag.toString("hex")}:${encrypted.toString("hex")}`;
}

/**
 * Decrypt a token previously encrypted by {@link encryptToken}.
 *
 * Parses the `iv:authTag:ciphertext` hex format, derives the AES-256 key
 * from the secret via SHA-256, and decrypts using AES-256-GCM. The GCM
 * authentication tag is verified during decryption — if the ciphertext or
 * tag has been tampered with, decryption fails and `null` is returned.
 *
 * @param encrypted - The encrypted string in `iv:authTag:ciphertext` hex format
 *   as produced by {@link encryptToken}.
 * @param secret - The same secret used during encryption (derives the AES-256 key).
 * @returns The decrypted plaintext string, or `null` if decryption fails for any
 *   reason (malformed input, wrong secret, tampered ciphertext, or invalid auth tag).
 *
 * @example
 * ```ts
 * const token = decryptToken(encrypted, process.env.NEXTAUTH_SECRET!);
 * if (!token) return new Response("Invalid session", { status: 401 });
 * ```
 */
export function decryptToken(
  encrypted: string,
  secret: string,
): string | null {
  try {
    const parts = encrypted.split(":");
    if (parts.length !== 3) return null;
    const [ivHex, authTagHex, ciphertextHex] = parts as [string, string, string];
    const key = deriveKey(secret);
    const iv = Buffer.from(ivHex, "hex");
    const authTag = Buffer.from(authTagHex, "hex");
    const ciphertext = Buffer.from(ciphertextHex, "hex");
    const decipher = createDecipheriv("aes-256-gcm", key, iv);
    decipher.setAuthTag(authTag);
    const decrypted = Buffer.concat([
      decipher.update(ciphertext),
      decipher.final(),
    ]);
    return decrypted.toString("utf8");
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Session cookie helpers
// ---------------------------------------------------------------------------

const COOKIE_NAME = "chapa_session";

interface SessionPayload {
  token: string;
  login: string;
  name: string | null;
  avatar_url: string;
}

/**
 * Encrypt a session payload into a `Set-Cookie` header value.
 *
 * Serializes the payload to JSON, encrypts it via {@link encryptToken}
 * (AES-256-GCM), and wraps it in cookie flags: HttpOnly, Secure (when HTTPS),
 * SameSite=Lax, Path=/, Max-Age=86400 (24 hours).
 *
 * @param payload - Session data containing token, login, name, and avatar_url
 * @param secret - The secret used to derive the AES-256 encryption key
 * @returns A `Set-Cookie` header string with the encrypted session
 */
export function createSessionCookie(
  payload: SessionPayload,
  secret: string,
): string {
  const json = JSON.stringify(payload);
  const encrypted = encryptToken(json, secret);
  return `${COOKIE_NAME}=${encrypted}; ${cookieFlags()}; Max-Age=86400`;
}

function isValidSessionPayload(value: unknown): value is SessionPayload {
  if (typeof value !== "object" || value === null) return false;
  const obj = value as Record<string, unknown>;
  if (typeof obj.login !== "string") return false;
  if (typeof obj.token !== "string") return false;
  if (obj.name !== null && typeof obj.name !== "string") return false;
  if (typeof obj.avatar_url !== "string") return false;
  return true;
}

/**
 * Read and decrypt the `chapa_session` cookie from a raw `Cookie` header.
 *
 * Extracts the session cookie by name, decrypts it via {@link decryptToken}
 * (AES-256-GCM), parses the resulting JSON, and validates the payload shape
 * before returning. Any failure at any stage (missing cookie, decryption error,
 * malformed JSON, invalid payload shape) returns `null` — never throws.
 *
 * The session payload contains the user's encrypted GitHub OAuth token,
 * login handle, display name, and avatar URL.
 *
 * **Cookie flags:** `HttpOnly`, `SameSite=Lax`, `Path=/`, `Secure` (when
 * served over HTTPS). Max-Age is 86400 (24 hours), set at creation time by
 * {@link createSessionCookie}.
 *
 * @param cookieHeader - Raw `Cookie` header string from the incoming request,
 *   or `null` if no cookies are present.
 * @param secret - The secret used to decrypt the session (same secret passed
 *   to {@link createSessionCookie} / {@link encryptToken}).
 * @returns The decrypted {@link SessionPayload} containing `token`, `login`,
 *   `name`, and `avatar_url`; or `null` if the cookie is absent, cannot be
 *   decrypted, or fails shape validation.
 *
 * @example
 * ```ts
 * const session = readSessionCookie(
 *   request.headers.get("cookie"),
 *   process.env.NEXTAUTH_SECRET!,
 * );
 * if (!session) return new Response("Unauthorized", { status: 401 });
 * // session.login, session.token, etc.
 * ```
 */
export function readSessionCookie(
  cookieHeader: string | null,
  secret: string,
): SessionPayload | null {
  if (!cookieHeader) return null;
  const match = cookieHeader
    .split(";")
    .map((c) => c.trim())
    .find((c) => c.startsWith(`${COOKIE_NAME}=`));
  if (!match) return null;
  const value = match.slice(COOKIE_NAME.length + 1);
  const json = decryptToken(value, secret);
  if (!json) return null;
  try {
    const parsed: unknown = JSON.parse(json);
    if (!isValidSessionPayload(parsed)) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Return a `Set-Cookie` header value that immediately expires the `chapa_session` cookie.
 *
 * @returns Set-Cookie header string with Max-Age=0
 */
export function clearSessionCookie(): string {
  return `${COOKIE_NAME}=; ${cookieFlags()}; Max-Age=0`;
}
