/**
 * Unsubscribe token generation and verification.
 *
 * Unsubscribe tokens are HMAC-SHA256 signed tokens embedded in email
 * unsubscribe links. They prove that the link was generated by the server
 * (for the specific handle it claims) before the route will act on it.
 *
 * Unlike CLI tokens, these tokens have no expiry — an old email with a
 * valid unsubscribe link should always work. The HMAC signature provides
 * ownership proof: only someone with NEXTAUTH_SECRET can forge a token.
 *
 * Format: base64url(handle).base64url(hmac_sha256(purpose:handle, secret))
 */

import "server-only";
import { createHmac, timingSafeEqual } from "crypto";

const PURPOSE = "unsubscribe";

/**
 * Generate an HMAC-signed unsubscribe token for a user handle.
 *
 * The token encodes the lowercase handle and a fixed purpose string.
 * It has no expiry — unsubscribe links in old emails must remain valid.
 *
 * @param handle - The GitHub handle (will be lowercased)
 * @param secret - The HMAC signing secret (NEXTAUTH_SECRET)
 * @returns A dot-separated signed token string safe for use in URLs
 */
export function generateUnsubscribeToken(
  handle: string,
  secret: string,
): string {
  const lower = handle.toLowerCase();
  const payload = Buffer.from(lower).toString("base64url");
  const message = `${PURPOSE}:${lower}`;
  const sig = createHmac("sha256", secret).update(message).digest("base64url");
  return `${payload}.${sig}`;
}

/**
 * Verify an HMAC-signed unsubscribe token for a given handle.
 *
 * Uses timing-safe comparison to prevent timing attacks. Returns true
 * only when the token was generated by this server for this exact handle.
 *
 * @param handle - The GitHub handle claimed by the request (will be lowercased)
 * @param token  - The dot-separated signed token from the URL
 * @param secret - The HMAC signing secret (NEXTAUTH_SECRET)
 * @returns true if the token is valid for this handle, false otherwise
 */
export function verifyUnsubscribeToken(
  handle: string,
  token: string,
  secret: string,
): boolean {
  if (!token) return false;

  const dotIndex = token.indexOf(".");
  if (dotIndex === -1) return false;

  const sig = token.slice(dotIndex + 1);
  if (!sig) return false;

  const lower = handle.toLowerCase();
  const message = `${PURPOSE}:${lower}`;
  const expectedSig = createHmac("sha256", secret)
    .update(message)
    .digest("base64url");

  const sigBuf = Buffer.from(sig);
  const expectedBuf = Buffer.from(expectedSig);

  if (sigBuf.length !== expectedBuf.length) return false;
  return timingSafeEqual(sigBuf, expectedBuf);
}
