#!/usr/bin/env node
// Emit a token-only CSS file into ds-bundle/tokens/.
//
// Why: the converter populates ds-bundle/tokens/ only from cfg.tokensPkg, which
// reads a node_modules package. Chapa keeps its tokens inline in
// apps/web/styles/globals.css, so tokens/ ships EMPTY. Anything downstream that
// wants the palette then has to scrape _ds_bundle.css, where 43 --color-* design
// tokens sit beside 71 --tw-* Tailwind engine variables.
//
// The engine variables cannot be removed from _ds_bundle.css: utilities
// dereference them at runtime, and their 71 @property blocks set the initial
// values. This script does not touch that file. It writes a separate manifest
// holding the design tokens only.
//
// Run after package-build.mjs, before upload.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const SRC = "apps/web/styles/globals.css";
const OUT_DIR = join("ds-bundle", "tokens");
const OUT = join(OUT_DIR, "chapa-tokens.css");


// Blocks that declare design tokens. Everything else in globals.css is
// utilities, keyframes and component rules, which belong in _ds_bundle.css.
//
// Since #1211 there is exactly one: every themed color is a single
// light-dark(<light>, <dark>) declaration inside @theme. The old :root and
// [data-theme="dark"] pair carried per-theme values; they now carry only
// color-scheme, so listing them here would scan two blocks that can never
// contain a token again.
const BLOCKS = ["@theme"];

function blockBody(source, selector) {
  const at = source.indexOf(selector + " {");
  if (at === -1) return null;
  let depth = 0;
  for (let i = source.indexOf("{", at); i < source.length; i++) {
    if (source[i] === "{") depth++;
    else if (source[i] === "}" && --depth === 0) {
      return source.slice(source.indexOf("{", at) + 1, i);
    }
  }
  return null;
}

/**
 * Pure transform: globals.css text in, manifest text out. Exported so a test
 * can exercise it directly rather than spawning this script as a subprocess.
 */
export function buildTokenCss(css) {
  const out = [
    "/* Generated by .design-sync/emit-tokens.mjs from apps/web/styles/globals.css.",
    "   Design tokens only: Tailwind engine variables are excluded. Do not edit by hand. */",
    "",
  ];
  let count = 0;

  for (const selector of BLOCKS) {
    const body = blockBody(css, selector);
    if (body === null) {
      console.error(`  [emit-tokens] block not found: ${selector}`);
      continue;
    }
    const decls = [...body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)]
      .filter(([, name]) => !name.startsWith("--tw-"))
      .map(([, name, value]) => `  ${name}: ${value.trim()};`);
    if (!decls.length) continue;
    count += decls.length;
    out.push(`${selector} {`, ...decls, "}", "");
  }

  return { css: out.join("\n"), count };
}

export { BLOCKS as TOKEN_BLOCKS, SRC as GLOBALS_CSS_PATH };

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { css, count } = buildTokenCss(readFileSync(SRC, "utf8"));
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, css, "utf8");
  console.error(`  [emit-tokens] ${count} design tokens -> ${OUT}`);
}
