#!/usr/bin/env node
// Emit a token-only CSS file into ds-bundle/tokens/.
//
// Why: the converter populates ds-bundle/tokens/ only from cfg.tokensPkg, which
// reads a node_modules package. Chapa keeps its tokens inline in
// apps/web/styles/globals.css, so tokens/ ships EMPTY. Anything downstream that
// wants the palette then has to scrape _ds_bundle.css, where 43 --color-* design
// tokens sit beside 71 --tw-* Tailwind engine variables.
//
// The engine variables cannot be removed from _ds_bundle.css: utilities
// dereference them at runtime, and their 71 @property blocks set the initial
// values. This script does not touch that file. It writes a separate manifest
// holding the design tokens only.
//
// Run after package-build.mjs, before upload.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const SRC = "apps/web/styles/globals.css";
const OUT_DIR = join("ds-bundle", "tokens");
const OUT = join(OUT_DIR, "chapa-tokens.css");

const css = readFileSync(SRC, "utf8");

// Blocks that declare design tokens. Everything else in globals.css is
// utilities, keyframes and component rules, which belong in _ds_bundle.css.
const BLOCKS = ["@theme", ":root", '[data-theme="dark"]'];

function blockBody(source, selector) {
  const at = source.indexOf(selector + " {");
  if (at === -1) return null;
  let depth = 0;
  for (let i = source.indexOf("{", at); i < source.length; i++) {
    if (source[i] === "{") depth++;
    else if (source[i] === "}" && --depth === 0) {
      return source.slice(source.indexOf("{", at) + 1, i);
    }
  }
  return null;
}

const out = [
  "/* Generated by .design-sync/emit-tokens.mjs from apps/web/styles/globals.css.",
  "   Design tokens only: Tailwind engine variables are excluded. Do not edit by hand. */",
  "",
];
let count = 0;

for (const selector of BLOCKS) {
  const body = blockBody(css, selector);
  if (body === null) {
    console.error(`  [emit-tokens] block not found: ${selector}`);
    continue;
  }
  const decls = [...body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)]
    .filter(([, name]) => !name.startsWith("--tw-"))
    .map(([, name, value]) => `  ${name}: ${value.trim()};`);
  if (!decls.length) continue;
  count += decls.length;
  out.push(`${selector} {`, ...decls, "}", "");
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, out.join("\n"), "utf8");
console.error(`  [emit-tokens] ${count} design tokens -> ${OUT}`);
