// @vitest-environment jsdom
import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, cleanup } from "@testing-library/react";

vi.mock("@/components/Navbar", () => ({
  Navbar: () => <nav data-testid="navbar" />,
}));

vi.mock("@/components/NavbarClient", () => ({
  NavbarClient: () => <nav data-testid="navbar" />,
}));

vi.mock("@/components/GlobalCommandBar", () => ({
  GlobalCommandBar: () => <div data-testid="command-bar" />,
}));

vi.mock("@/components/GlobalCommandBarLazy", () => ({
  GlobalCommandBarLazy: () => <div data-testid="command-bar" />,
}));

vi.mock("@/lib/i18n/server", () => ({
  getServerT: vi.fn().mockReturnValue((key: string) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const map: Record<string, any> = {
      "about.verification.h1": "Badge Verification",
      "about.verification.intro": "Every Chapa badge carries a verification hash that proves the data has not been tampered with.",
      "about.verification.sectionWhy": "Why verification exists",
      "about.verification.whyBody1": "Chapa badges are embeddable SVGs.",
      "about.verification.whyBody2Prefix": "Anyone can paste it into the ",
      "about.verification.verifyPageLink": "verification page",
      "about.verification.whyBody2Suffix": " to confirm the badge is authentic.",
      "about.verification.sectionHow": "How it works",
      "about.verification.howIntro": "The hash is generated using ",
      "about.verification.howHighlight": "HMAC-SHA256",
      "about.verification.howSuffix": ", a widely used, industry-standard message authentication code.",
      "about.verification.howStep1Heading": "Build a deterministic payload",
      "about.verification.howStep1Body": " — the badge data fields are concatenated in a fixed order.",
      "about.verification.howStep2Heading": "Sign the payload",
      "about.verification.howStep2Body": " — the payload is signed with a secret key.",
      "about.verification.howStep3Heading": "Truncate to 32 characters",
      "about.verification.howStep3Body": " — the first 32 hex characters are used.",
      "about.verification.howStorageNote": "When a badge is generated, the verification record is stored server-side.",
      "about.verification.sectionWhat": "What data is signed",
      "about.verification.whatIntro": "The HMAC payload includes every meaningful field displayed on the badge:",
      "about.verification.whatTableHeaders": ["Field", "Example", "Why included"],
      "about.verification.whatTableRows": [["Handle", "juan294", "Ties the badge to a specific developer"]],
      "about.verification.whatDeterministicNote": "Floating-point dimension scores are rounded to integers before signing.",
      "about.verification.sectionGuarantees": "What it guarantees",
      "about.verification.guaranteeDataIntegrityHeading": "Data integrity",
      "about.verification.guaranteeDataIntegritySuffix": " — if any field has been altered, the hash will not match.",
      "about.verification.guaranteeAuthenticityHeading": "Authenticity",
      "about.verification.guaranteeAuthenticitySuffix": " — only the Chapa server can produce a valid hash.",
      "about.verification.guaranteeDateHeading": "Date binding",
      "about.verification.guaranteeDateSuffix": " — the date is part of the payload.",
      "about.verification.sectionLimits": "What it does not guarantee",
      "about.verification.limitsIntro": "Transparency means being honest about limitations too:",
      "about.verification.limitNotBlockchainHeading": "Not a blockchain",
      "about.verification.limitNotBlockchainSuffix": " — verification records are stored in a database with a 30-day TTL.",
      "about.verification.limitTrustHeading": "Trust in Chapa",
      "about.verification.limitTrustSuffix": " — the system proves the badge was generated by Chapa.",
      "about.verification.limitNotTamperProofHeading": "Not tamper-proof at the SVG level",
      "about.verification.limitNotTamperProofSuffix": " — anyone can edit an SVG file.",
      "about.verification.sectionHowTo": "How to verify a badge",
      "about.verification.howToStep1": "Find the 32-character hex code on the right edge of any Chapa badge.",
      "about.verification.howToStep2Prefix": "Go to the ",
      "about.verification.howToStep2Link": "verification page",
      "about.verification.howToStep2Suffix": " and enter the code.",
      "about.verification.howToStep3": "The result will show the original badge data.",
      "about.verification.howToApiPrefix": "You can also use the API directly: ",
      "about.verification.howToApiSuffix": " returns a JSON response.",
      "about.verification.howToRateLimit": "Rate-limited to 30 requests per minute per IP.",
      "about.verification.sectionDesign": "Design decisions",
      "about.verification.designTableHeaders": ["Decision", "Rationale"],
      "about.verification.designTableRows": [["HMAC-SHA256", "Industry standard, widely audited."]],
      "about.verification.ctaHeading": "Try it yourself",
      "about.verification.ctaBody": "Every Chapa badge has a verification hash.",
      "about.verification.ctaButton": "Verify a Badge",
      "about.verification.metadataTitle": "Badge Verification",
      "about.verification.metadataDescription": "How Chapa badges are verified.",
      "about.verification.ogTitle": "Chapa Badge Verification",
      "about.verification.ogDescription": "How the verification hash works.",
      "about.verification.twitterTitle": "Chapa Badge Verification",
      "about.verification.twitterDescription": "How the verification hash works.",
    };
    return map[key] ?? key;
  }),
}));

// #1023 (FE-H1) — VerificationPageContent no longer reads translation via
// the client useTranslation() context; it receives `t` (getServerT(locale))
// as a prop, with `locale` sourced from the route's [locale] segment param.

afterEach(cleanup);

describe("VerificationPage render", () => {
  it("renders the page heading", async () => {
    const { default: VerificationPage } = await import("./page");
    render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    expect(screen.getByText("Badge Verification")).toBeDefined();
  });

  it("renders the navbar", async () => {
    const { default: VerificationPage } = await import("./page");
    render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    expect(screen.getByTestId("navbar")).toBeDefined();
  });

  it("renders the command bar", async () => {
    const { default: VerificationPage } = await import("./page");
    render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    expect(screen.getByTestId("command-bar")).toBeDefined();
  });

  it("renders section headings about how verification works", async () => {
    const { default: VerificationPage } = await import("./page");
    render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    expect(screen.getByText("Why verification exists")).toBeDefined();
    expect(screen.getByText("How it works")).toBeDefined();
    expect(screen.getByText("What data is signed")).toBeDefined();
  });

  it("renders tables with verification field data", async () => {
    const { default: VerificationPage } = await import("./page");
    const { container } = render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    const tables = container.querySelectorAll("table");
    expect(tables.length).toBeGreaterThan(0);
  });

  it("renders the ShieldCheckIcon and ArrowRightIcon in CTA", async () => {
    const { default: VerificationPage } = await import("./page");
    const { container } = render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    const svgs = container.querySelectorAll("svg");
    expect(svgs.length).toBeGreaterThan(0);
  });

  it("renders the CTA section", async () => {
    const { default: VerificationPage } = await import("./page");
    render(await VerificationPage({ params: Promise.resolve({ locale: "en" }) }));
    expect(screen.getByText("Try it yourself")).toBeDefined();
    expect(screen.getByText("Verify a Badge")).toBeDefined();
  });
});

describe("VerificationPage generateMetadata", () => {
  it("returns metadata with title and openGraph", async () => {
    const { generateMetadata } = await import("./page");
    const meta = await generateMetadata({ params: Promise.resolve({ locale: "en" }) });
    expect(meta.title).toBeTruthy();
    expect(meta.openGraph).toBeDefined();
    expect(meta.twitter).toBeDefined();
  });

  it("returns metadata with a title", async () => {
    const { generateMetadata } = await import("./page");
    const meta = await generateMetadata({ params: Promise.resolve({ locale: "en" }) });
    expect(meta.title).toBeTruthy();
  });
});
