export const CURRENT_VERIFICATION_HASH_HEX_LENGTH = 32;
export const VERIFICATION_HASH_PATTERN =
  /^(?:[0-9a-f]{8}|[0-9a-f]{16}|[0-9a-f]{32})$/;
export const VERIFICATION_RECORD_TTL_DAYS = 30;
export const VERIFICATION_RECORD_TTL_MS =
  VERIFICATION_RECORD_TTL_DAYS * 24 * 60 * 60 * 1000;
