import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { scoringConsistencyFixture } from "@/lib/profile/__fixtures__/scoring-consistency";
const mocks = vi.hoisted(() => ({ receipt: vi.fn(), issue: vi.fn(), materialize: vi.fn(), selection: vi.fn() }));
vi.mock("@/lib/auth/resolve-request-auth", () => ({ resolveRequestAuth: vi.fn().mockResolvedValue({ handle: "alice", token: "secret" }) }));
vi.mock("@/lib/cache/redis", () => ({ rateLimit: vi.fn().mockResolvedValue({ allowed: true }) }));
vi.mock("@/lib/scoring-render-selection", () => ({ readScoringRenderSelection: mocks.selection }));
vi.mock("@/lib/profile/orchestrated-profile", () => ({ materializeOrchestratedProfile: mocks.materialize, persistOrchestratedSnapshot: vi.fn().mockResolvedValue(true) }));
vi.mock("@/lib/profile/issue-receipt", () => ({ issueScoreReceiptIfConsented: mocks.issue }));
vi.mock("@/lib/db/score-receipts-observed", () => ({ dbReadObservedReceipt: mocks.receipt }));
vi.mock("@/lib/profile/post-write-invalidation", () => ({ invalidateProfileReadModels: vi.fn() }));
vi.mock("@/lib/cache/craft-cache", () => ({ updateCraftCache: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
import { POST } from "./route";
const selected = { enabled: true, machinePolicy: "v7.2", cacheable: true, capturedAt: Date.parse("2026-09-08T10:00:00Z") };
beforeEach(() => { vi.clearAllMocks(); mocks.selection.mockResolvedValue(selected); mocks.issue.mockResolvedValue("issued"); });
describe("recalculation publishes one final current score", () => {
  it.each([57, 0] as const)("responds with published core46/report%s after legacy80 persistence", async craft => {
    const fixture = await scoringConsistencyFixture({ craft });
    mocks.materialize.mockResolvedValue({ stats: fixture.stats, displayImpact: fixture.impact, rawImpact: fixture.impact, statsComplete: true, craftResult: null });
    mocks.receipt.mockResolvedValue({ status: "found", envelope: fixture.envelope, trend: null, isCurrent: true });
    const response = await POST(new NextRequest("https://chapa.test/api/recalculate", { method: "POST" }), undefined);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toMatchObject({ adjustedComposite: 46, compositeScore: 46, displayScore: 46, archetype: null, publication: "published", craft: { status: "scored", report: { result: { point: { exact: craft } } } }, legacy: { impact: { adjustedComposite: 80 } } });
    expect(mocks.selection).toHaveBeenCalledTimes(1);
    expect(mocks.issue).toHaveBeenCalledWith("alice", expect.objectContaining({ scoringSelection: selected }));
    expect(mocks.issue.mock.invocationCallOrder[0]).toBeLessThan(mocks.receipt.mock.invocationCallOrder[0]!);
  });
});
